# Generated by Django 3.0.5 on 2020-05-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenario_generator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, default='null', max_length=50)),
                ('headers', models.CharField(default='null', max_length=1000)),
                ('s0', models.CharField(max_length=1000)),
                ('ar', models.CharField(default='null', max_length=1000)),
                ('mu', models.CharField(max_length=1000)),
                ('sigma', models.CharField(max_length=1000)),
                ('corr', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, default='null', max_length=50)),
                ('headers', models.CharField(blank=True, default='null', max_length=1000)),
                ('ts', models.CharField(max_length=1000000)),
            ],
        ),
    ]
